### ISSUE TITLE
How to resolve incomplete /imu/data fields

### ISSUE THREAD

**Issue by Scottapotamas** [ethz-asl/ethzasl_xsens_driver#91]
I've not seen much regarding the 'expected' output on /imu/data from the xsens_driver, I've got issues with the inbound messages containing any combination of orientation, vel and acc, with the values going to { 0 } often.

Do I need to modify the default sampling rates/try and sync them?

A plot shows the effect quite well:

![image](https://user-images.githubusercontent.com/460325/46986639-03631900-d138-11e8-9403-09702d757153.png)

```
header: 
  seq: 374343
  stamp: 
    secs: 1539651457
    nsecs: 343955039
  frame_id: /imu
orientation: 
  x: -0.00382859236561
  y: 0.00172457203735
  z: 0.999918520451
  w: 0.0120584191754
orientation_covariance: [0.01745, 0.0, 0.0, 0.0, 0.01745, 0.0, 0.0, 0.0, 0.15708]
angular_velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
linear_acceleration: 
  x: -0.0229027047753
  y: 0.0022353194654
  z: 0.016420841217
linear_acceleration_covariance: [0.0004, 0.0, 0.0, 0.0, 0.0004, 0.0, 0.0, 0.0, 0.0004]
---
header: 
  seq: 374344
  stamp: 
    secs: 1539651457
    nsecs: 348462104
  frame_id: /imu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
angular_velocity: 
  x: -0.00361352227628
  y: -0.00345708127134
  z: 0.000307317939587
angular_velocity_covariance: [0.0004, 0.0, 0.0, 0.0, 0.0004, 0.0, 0.0, 0.0, 0.0004]
linear_acceleration: 
  x: -0.077241808176
  y: 0.0415544435382
  z: 9.81361865997
linear_acceleration_covariance: [0.0004, 0.0, 0.0, 0.0, 0.0004, 0.0, 0.0, 0.0, 0.0004]
---
^Cheader: 
  seq: 374345
  stamp: 
    secs: 1539651457
    nsecs: 353487014
  frame_id: /imu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
angular_velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
linear_acceleration: 
  x: 0.0101052280515
  y: -0.0128167485818
  z: -0.00693368911743
linear_acceleration_covariance: [0.0004, 0.0, 0.0, 0.0, 0.0004, 0.0, 0.0, 0.0, 0.0004]
```

I'm trying to work with a MTi-300 over USB, running an Odroid XU4 (armhf), Ubuntu 16.04, Kinetic.

I launched it with the standard `roslaunch xsens_driver xsens_driver.launch`. Could this be an configuration issue perhaps? I've tried this with two MTi-300 units and one of them is _better_ but still exhibits the issue.
